"""add image_url to nutrition records

Revision ID: b819e5f3437b
Revises: 006def0142cd
Create Date: 2025-01-16 23:16:13.363437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b819e5f3437b'
down_revision: Union[str, None] = '006def0142cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_records', sa.Column('image_url', sa.String(255), nullable=True))
    op.alter_column('nutrition_records', 'protein_explanation',
               existing_type=sa.VARCHAR(500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('nutrition_records', 'fat_explanation',
               existing_type=sa.VARCHAR(500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('nutrition_records', 'impact_explanation',
               existing_type=sa.VARCHAR(500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('nutrition_records', 'best_time',
               existing_type=sa.VARCHAR(100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nutrition_records', 'best_time',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(100),
               existing_nullable=True)
    op.alter_column('nutrition_records', 'impact_explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(500),
               existing_nullable=True)
    op.alter_column('nutrition_records', 'fat_explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(500),
               existing_nullable=True)
    op.alter_column('nutrition_records', 'protein_explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(500),
               existing_nullable=True)
    op.drop_column('nutrition_records', 'image_url')
    # ### end Alembic commands ###
